name: Deploy Automatico
run-name: ${{github.actor}} is testing out GitHub Actions
on:
  push:
    branches:
      - develop

jobs:
    develop:
        runs-on: ubuntu-latest
        environment:
            name: develop
        steps:
            - name: Setup SSH
              run: |
                mkdir -p ~/.ssh/
                echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                ssh-keyscan -H 18.231.210.229 >> ~/.ssh/known_hosts
            - name: Deploy
              run: |
                 ssh ubuntu@18.231.210.229 'whoami && sudo bash /var/www/update.sh floodMap'
                 
on:
  push:
    branches:
      - homolog

jobs:
    homolog:
        runs-on: ubuntu-latest
        environment:
            name: homolog
        steps:
            - name: Setup SSH
              run: |
                mkdir -p ~/.ssh/
                echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                ssh-keyscan -H 18.228.37.157 >> ~/.ssh/known_hosts
            - name: Deploy
              run: |
                 ssh ubuntu@18.228.37.157 'whoami && sudo bash /var/www/update.sh floodMap'                 
                 
on: 
  push:
    branches:
      - main

jobs: 
    production:
        runs-on: ubuntu-latest
        environment:
            name: prod
        steps:
            - name: Setup SSH
              run: |
                mkdir -p ~/.ssh/
                echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts
            - name: Deploy
              run: |
                 ssh ${{ secrets.USER_IP }} 'whoami && bash /var/www/update.sh floodMap'                 
